// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: proto/Starwars.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBrokerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Planeta string `protobuf:"bytes,1,opt,name=planeta,proto3" json:"planeta,omitempty"`
	Ciudad  string `protobuf:"bytes,2,opt,name=ciudad,proto3" json:"ciudad,omitempty"`
}

func (x *GetBrokerRequest) Reset() {
	*x = GetBrokerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Starwars_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBrokerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrokerRequest) ProtoMessage() {}

func (x *GetBrokerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Starwars_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrokerRequest.ProtoReflect.Descriptor instead.
func (*GetBrokerRequest) Descriptor() ([]byte, []int) {
	return file_proto_Starwars_proto_rawDescGZIP(), []int{0}
}

func (x *GetBrokerRequest) GetPlaneta() string {
	if x != nil {
		return x.Planeta
	}
	return ""
}

func (x *GetBrokerRequest) GetCiudad() string {
	if x != nil {
		return x.Ciudad
	}
	return ""
}

type GetBrokerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Servidor string `protobuf:"bytes,3,opt,name=servidor,proto3" json:"servidor,omitempty"`
}

func (x *GetBrokerReply) Reset() {
	*x = GetBrokerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Starwars_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBrokerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBrokerReply) ProtoMessage() {}

func (x *GetBrokerReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Starwars_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBrokerReply.ProtoReflect.Descriptor instead.
func (*GetBrokerReply) Descriptor() ([]byte, []int) {
	return file_proto_Starwars_proto_rawDescGZIP(), []int{1}
}

func (x *GetBrokerReply) GetServidor() string {
	if x != nil {
		return x.Servidor
	}
	return ""
}

type GetServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Planeta string `protobuf:"bytes,1,opt,name=planeta,proto3" json:"planeta,omitempty"`
	Ciudad  string `protobuf:"bytes,2,opt,name=ciudad,proto3" json:"ciudad,omitempty"`
}

func (x *GetServerRequest) Reset() {
	*x = GetServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Starwars_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerRequest) ProtoMessage() {}

func (x *GetServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Starwars_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerRequest.ProtoReflect.Descriptor instead.
func (*GetServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_Starwars_proto_rawDescGZIP(), []int{2}
}

func (x *GetServerRequest) GetPlaneta() string {
	if x != nil {
		return x.Planeta
	}
	return ""
}

func (x *GetServerRequest) GetCiudad() string {
	if x != nil {
		return x.Ciudad
	}
	return ""
}

type GetServerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rebeldes int32   `protobuf:"varint,1,opt,name=rebeldes,proto3" json:"rebeldes,omitempty"`
	Reloj    []int32 `protobuf:"varint,2,rep,packed,name=reloj,proto3" json:"reloj,omitempty"`
	Servidor string  `protobuf:"bytes,3,opt,name=servidor,proto3" json:"servidor,omitempty"`
}

func (x *GetServerReply) Reset() {
	*x = GetServerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Starwars_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerReply) ProtoMessage() {}

func (x *GetServerReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Starwars_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerReply.ProtoReflect.Descriptor instead.
func (*GetServerReply) Descriptor() ([]byte, []int) {
	return file_proto_Starwars_proto_rawDescGZIP(), []int{3}
}

func (x *GetServerReply) GetRebeldes() int32 {
	if x != nil {
		return x.Rebeldes
	}
	return 0
}

func (x *GetServerReply) GetReloj() []int32 {
	if x != nil {
		return x.Reloj
	}
	return nil
}

func (x *GetServerReply) GetServidor() string {
	if x != nil {
		return x.Servidor
	}
	return ""
}

type MergeLeiaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Planeta string `protobuf:"bytes,1,opt,name=planeta,proto3" json:"planeta,omitempty"`
	Ciudad  string `protobuf:"bytes,2,opt,name=ciudad,proto3" json:"ciudad,omitempty"`
}

func (x *MergeLeiaRequest) Reset() {
	*x = MergeLeiaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Starwars_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeLeiaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeLeiaRequest) ProtoMessage() {}

func (x *MergeLeiaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Starwars_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeLeiaRequest.ProtoReflect.Descriptor instead.
func (*MergeLeiaRequest) Descriptor() ([]byte, []int) {
	return file_proto_Starwars_proto_rawDescGZIP(), []int{4}
}

func (x *MergeLeiaRequest) GetPlaneta() string {
	if x != nil {
		return x.Planeta
	}
	return ""
}

func (x *MergeLeiaRequest) GetCiudad() string {
	if x != nil {
		return x.Ciudad
	}
	return ""
}

type MergeLeiaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rebeldes int32   `protobuf:"varint,1,opt,name=rebeldes,proto3" json:"rebeldes,omitempty"`
	Reloj    []int32 `protobuf:"varint,2,rep,packed,name=reloj,proto3" json:"reloj,omitempty"`
	Servidor string  `protobuf:"bytes,3,opt,name=servidor,proto3" json:"servidor,omitempty"`
}

func (x *MergeLeiaReply) Reset() {
	*x = MergeLeiaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Starwars_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MergeLeiaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeLeiaReply) ProtoMessage() {}

func (x *MergeLeiaReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Starwars_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeLeiaReply.ProtoReflect.Descriptor instead.
func (*MergeLeiaReply) Descriptor() ([]byte, []int) {
	return file_proto_Starwars_proto_rawDescGZIP(), []int{5}
}

func (x *MergeLeiaReply) GetRebeldes() int32 {
	if x != nil {
		return x.Rebeldes
	}
	return 0
}

func (x *MergeLeiaReply) GetReloj() []int32 {
	if x != nil {
		return x.Reloj
	}
	return nil
}

func (x *MergeLeiaReply) GetServidor() string {
	if x != nil {
		return x.Servidor
	}
	return ""
}

var File_proto_Starwars_proto protoreflect.FileDescriptor

var file_proto_Starwars_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x53, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x69, 0x75, 0x64, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x69, 0x75,
	0x64, 0x61, 0x64, 0x22, 0x2c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f,
	0x72, 0x22, 0x44, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x69, 0x75, 0x64, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x69, 0x75, 0x64, 0x61, 0x64, 0x22, 0x5e, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x62,
	0x65, 0x6c, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x62,
	0x65, 0x6c, 0x64, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x72, 0x65, 0x6c, 0x6f, 0x6a, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x22, 0x44, 0x0a, 0x10, 0x4d, 0x65, 0x72, 0x67, 0x65,
	0x4c, 0x65, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x6c, 0x61, 0x6e, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6c,
	0x61, 0x6e, 0x65, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x69, 0x75, 0x64, 0x61, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x69, 0x75, 0x64, 0x61, 0x64, 0x22, 0x5e, 0x0a,
	0x0e, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x4c, 0x65, 0x69, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x72, 0x65, 0x62, 0x65, 0x6c, 0x64, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x72,
	0x65, 0x6c, 0x6f, 0x6a, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x72, 0x65, 0x6c, 0x6f,
	0x6a, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x64, 0x6f, 0x72, 0x32, 0xe3, 0x01,
	0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x49,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x61, 0x6e, 0x74, 0x53, 0x6f, 0x6c, 0x64, 0x61, 0x64, 0x6f,
	0x73, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x72, 0x6f, 0x6b,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x6e, 0x74, 0x53, 0x6f, 0x6c, 0x64, 0x61, 0x64, 0x6f, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x09, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x4c, 0x65, 0x69,
	0x61, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x4c,
	0x65, 0x69, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x4c, 0x65, 0x69, 0x61, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x6c, 0x61, 0x62, 0x33, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_Starwars_proto_rawDescOnce sync.Once
	file_proto_Starwars_proto_rawDescData = file_proto_Starwars_proto_rawDesc
)

func file_proto_Starwars_proto_rawDescGZIP() []byte {
	file_proto_Starwars_proto_rawDescOnce.Do(func() {
		file_proto_Starwars_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_Starwars_proto_rawDescData)
	})
	return file_proto_Starwars_proto_rawDescData
}

var file_proto_Starwars_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_Starwars_proto_goTypes = []interface{}{
	(*GetBrokerRequest)(nil), // 0: proto.GetBrokerRequest
	(*GetBrokerReply)(nil),   // 1: proto.GetBrokerReply
	(*GetServerRequest)(nil), // 2: proto.GetServerRequest
	(*GetServerReply)(nil),   // 3: proto.GetServerReply
	(*MergeLeiaRequest)(nil), // 4: proto.MergeLeiaRequest
	(*MergeLeiaReply)(nil),   // 5: proto.MergeLeiaReply
}
var file_proto_Starwars_proto_depIdxs = []int32{
	0, // 0: proto.StarwarsGame.GetCantSoldadosBroker:input_type -> proto.GetBrokerRequest
	2, // 1: proto.StarwarsGame.GetCantSoldadosServer:input_type -> proto.GetServerRequest
	4, // 2: proto.StarwarsGame.MergeLeia:input_type -> proto.MergeLeiaRequest
	1, // 3: proto.StarwarsGame.GetCantSoldadosBroker:output_type -> proto.GetBrokerReply
	3, // 4: proto.StarwarsGame.GetCantSoldadosServer:output_type -> proto.GetServerReply
	5, // 5: proto.StarwarsGame.MergeLeia:output_type -> proto.MergeLeiaReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_Starwars_proto_init() }
func file_proto_Starwars_proto_init() {
	if File_proto_Starwars_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_Starwars_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBrokerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Starwars_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBrokerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Starwars_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Starwars_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetServerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Starwars_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeLeiaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Starwars_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MergeLeiaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_Starwars_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_Starwars_proto_goTypes,
		DependencyIndexes: file_proto_Starwars_proto_depIdxs,
		MessageInfos:      file_proto_Starwars_proto_msgTypes,
	}.Build()
	File_proto_Starwars_proto = out.File
	file_proto_Starwars_proto_rawDesc = nil
	file_proto_Starwars_proto_goTypes = nil
	file_proto_Starwars_proto_depIdxs = nil
}
