// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StarwarsGameClient is the client API for StarwarsGame service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StarwarsGameClient interface {
	// Funciones para Leia
	GetCantSoldadosBroker(ctx context.Context, in *GetBrokerRequest, opts ...grpc.CallOption) (*GetBrokerReply, error)
	GetCantSoldadosServer(ctx context.Context, in *GetServerRequest, opts ...grpc.CallOption) (*GetServerReply, error)
	MergeLeiaBroker(ctx context.Context, in *MergeLeiaRequest, opts ...grpc.CallOption) (*MergeLeiaReply, error)
	MergeLeiaServer(ctx context.Context, in *MergeLeiaServerRequest, opts ...grpc.CallOption) (*MergeLeiaServerReply, error)
	// Funciones para Informantes
	AskForServers(ctx context.Context, in *AskForServersRequest, opts ...grpc.CallOption) (*AskForServersReply, error)
	AskedServer(ctx context.Context, in *AskedServerRequest, opts ...grpc.CallOption) (*AskedServerReply, error)
	GetCantSoldados(ctx context.Context, in *GetCantSoldadosRequest, opts ...grpc.CallOption) (*GetCantSoldadosReply, error)
	MergeInformanteServer(ctx context.Context, in *MergeInformanteServerRequest, opts ...grpc.CallOption) (*MergeInformanteServerReply, error)
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsReply, error)
	PostMerge(ctx context.Context, in *PostMergeRequest, opts ...grpc.CallOption) (*PostMergeReply, error)
}

type starwarsGameClient struct {
	cc grpc.ClientConnInterface
}

func NewStarwarsGameClient(cc grpc.ClientConnInterface) StarwarsGameClient {
	return &starwarsGameClient{cc}
}

func (c *starwarsGameClient) GetCantSoldadosBroker(ctx context.Context, in *GetBrokerRequest, opts ...grpc.CallOption) (*GetBrokerReply, error) {
	out := new(GetBrokerReply)
	err := c.cc.Invoke(ctx, "/proto.StarwarsGame/GetCantSoldadosBroker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsGameClient) GetCantSoldadosServer(ctx context.Context, in *GetServerRequest, opts ...grpc.CallOption) (*GetServerReply, error) {
	out := new(GetServerReply)
	err := c.cc.Invoke(ctx, "/proto.StarwarsGame/GetCantSoldadosServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsGameClient) MergeLeiaBroker(ctx context.Context, in *MergeLeiaRequest, opts ...grpc.CallOption) (*MergeLeiaReply, error) {
	out := new(MergeLeiaReply)
	err := c.cc.Invoke(ctx, "/proto.StarwarsGame/MergeLeiaBroker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsGameClient) MergeLeiaServer(ctx context.Context, in *MergeLeiaServerRequest, opts ...grpc.CallOption) (*MergeLeiaServerReply, error) {
	out := new(MergeLeiaServerReply)
	err := c.cc.Invoke(ctx, "/proto.StarwarsGame/MergeLeiaServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsGameClient) AskForServers(ctx context.Context, in *AskForServersRequest, opts ...grpc.CallOption) (*AskForServersReply, error) {
	out := new(AskForServersReply)
	err := c.cc.Invoke(ctx, "/proto.StarwarsGame/AskForServers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsGameClient) AskedServer(ctx context.Context, in *AskedServerRequest, opts ...grpc.CallOption) (*AskedServerReply, error) {
	out := new(AskedServerReply)
	err := c.cc.Invoke(ctx, "/proto.StarwarsGame/AskedServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsGameClient) GetCantSoldados(ctx context.Context, in *GetCantSoldadosRequest, opts ...grpc.CallOption) (*GetCantSoldadosReply, error) {
	out := new(GetCantSoldadosReply)
	err := c.cc.Invoke(ctx, "/proto.StarwarsGame/GetCantSoldados", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsGameClient) MergeInformanteServer(ctx context.Context, in *MergeInformanteServerRequest, opts ...grpc.CallOption) (*MergeInformanteServerReply, error) {
	out := new(MergeInformanteServerReply)
	err := c.cc.Invoke(ctx, "/proto.StarwarsGame/MergeInformanteServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsGameClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (*GetLogsReply, error) {
	out := new(GetLogsReply)
	err := c.cc.Invoke(ctx, "/proto.StarwarsGame/GetLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *starwarsGameClient) PostMerge(ctx context.Context, in *PostMergeRequest, opts ...grpc.CallOption) (*PostMergeReply, error) {
	out := new(PostMergeReply)
	err := c.cc.Invoke(ctx, "/proto.StarwarsGame/PostMerge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StarwarsGameServer is the server API for StarwarsGame service.
// All implementations must embed UnimplementedStarwarsGameServer
// for forward compatibility
type StarwarsGameServer interface {
	// Funciones para Leia
	GetCantSoldadosBroker(context.Context, *GetBrokerRequest) (*GetBrokerReply, error)
	GetCantSoldadosServer(context.Context, *GetServerRequest) (*GetServerReply, error)
	MergeLeiaBroker(context.Context, *MergeLeiaRequest) (*MergeLeiaReply, error)
	MergeLeiaServer(context.Context, *MergeLeiaServerRequest) (*MergeLeiaServerReply, error)
	// Funciones para Informantes
	AskForServers(context.Context, *AskForServersRequest) (*AskForServersReply, error)
	AskedServer(context.Context, *AskedServerRequest) (*AskedServerReply, error)
	GetCantSoldados(context.Context, *GetCantSoldadosRequest) (*GetCantSoldadosReply, error)
	MergeInformanteServer(context.Context, *MergeInformanteServerRequest) (*MergeInformanteServerReply, error)
	GetLogs(context.Context, *GetLogsRequest) (*GetLogsReply, error)
	PostMerge(context.Context, *PostMergeRequest) (*PostMergeReply, error)
	mustEmbedUnimplementedStarwarsGameServer()
}

// UnimplementedStarwarsGameServer must be embedded to have forward compatible implementations.
type UnimplementedStarwarsGameServer struct {
}

func (UnimplementedStarwarsGameServer) GetCantSoldadosBroker(context.Context, *GetBrokerRequest) (*GetBrokerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCantSoldadosBroker not implemented")
}
func (UnimplementedStarwarsGameServer) GetCantSoldadosServer(context.Context, *GetServerRequest) (*GetServerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCantSoldadosServer not implemented")
}
func (UnimplementedStarwarsGameServer) MergeLeiaBroker(context.Context, *MergeLeiaRequest) (*MergeLeiaReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MergeLeiaBroker not implemented")
}
func (UnimplementedStarwarsGameServer) MergeLeiaServer(context.Context, *MergeLeiaServerRequest) (*MergeLeiaServerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MergeLeiaServer not implemented")
}
func (UnimplementedStarwarsGameServer) AskForServers(context.Context, *AskForServersRequest) (*AskForServersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AskForServers not implemented")
}
func (UnimplementedStarwarsGameServer) AskedServer(context.Context, *AskedServerRequest) (*AskedServerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AskedServer not implemented")
}
func (UnimplementedStarwarsGameServer) GetCantSoldados(context.Context, *GetCantSoldadosRequest) (*GetCantSoldadosReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCantSoldados not implemented")
}
func (UnimplementedStarwarsGameServer) MergeInformanteServer(context.Context, *MergeInformanteServerRequest) (*MergeInformanteServerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MergeInformanteServer not implemented")
}
func (UnimplementedStarwarsGameServer) GetLogs(context.Context, *GetLogsRequest) (*GetLogsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedStarwarsGameServer) PostMerge(context.Context, *PostMergeRequest) (*PostMergeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostMerge not implemented")
}
func (UnimplementedStarwarsGameServer) mustEmbedUnimplementedStarwarsGameServer() {}

// UnsafeStarwarsGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StarwarsGameServer will
// result in compilation errors.
type UnsafeStarwarsGameServer interface {
	mustEmbedUnimplementedStarwarsGameServer()
}

func RegisterStarwarsGameServer(s grpc.ServiceRegistrar, srv StarwarsGameServer) {
	s.RegisterService(&StarwarsGame_ServiceDesc, srv)
}

func _StarwarsGame_GetCantSoldadosBroker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBrokerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsGameServer).GetCantSoldadosBroker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StarwarsGame/GetCantSoldadosBroker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsGameServer).GetCantSoldadosBroker(ctx, req.(*GetBrokerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarwarsGame_GetCantSoldadosServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsGameServer).GetCantSoldadosServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StarwarsGame/GetCantSoldadosServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsGameServer).GetCantSoldadosServer(ctx, req.(*GetServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarwarsGame_MergeLeiaBroker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeLeiaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsGameServer).MergeLeiaBroker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StarwarsGame/MergeLeiaBroker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsGameServer).MergeLeiaBroker(ctx, req.(*MergeLeiaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarwarsGame_MergeLeiaServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeLeiaServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsGameServer).MergeLeiaServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StarwarsGame/MergeLeiaServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsGameServer).MergeLeiaServer(ctx, req.(*MergeLeiaServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarwarsGame_AskForServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskForServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsGameServer).AskForServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StarwarsGame/AskForServers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsGameServer).AskForServers(ctx, req.(*AskForServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarwarsGame_AskedServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskedServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsGameServer).AskedServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StarwarsGame/AskedServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsGameServer).AskedServer(ctx, req.(*AskedServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarwarsGame_GetCantSoldados_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCantSoldadosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsGameServer).GetCantSoldados(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StarwarsGame/GetCantSoldados",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsGameServer).GetCantSoldados(ctx, req.(*GetCantSoldadosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarwarsGame_MergeInformanteServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeInformanteServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsGameServer).MergeInformanteServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StarwarsGame/MergeInformanteServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsGameServer).MergeInformanteServer(ctx, req.(*MergeInformanteServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarwarsGame_GetLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsGameServer).GetLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StarwarsGame/GetLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsGameServer).GetLogs(ctx, req.(*GetLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StarwarsGame_PostMerge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMergeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StarwarsGameServer).PostMerge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StarwarsGame/PostMerge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StarwarsGameServer).PostMerge(ctx, req.(*PostMergeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StarwarsGame_ServiceDesc is the grpc.ServiceDesc for StarwarsGame service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StarwarsGame_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StarwarsGame",
	HandlerType: (*StarwarsGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCantSoldadosBroker",
			Handler:    _StarwarsGame_GetCantSoldadosBroker_Handler,
		},
		{
			MethodName: "GetCantSoldadosServer",
			Handler:    _StarwarsGame_GetCantSoldadosServer_Handler,
		},
		{
			MethodName: "MergeLeiaBroker",
			Handler:    _StarwarsGame_MergeLeiaBroker_Handler,
		},
		{
			MethodName: "MergeLeiaServer",
			Handler:    _StarwarsGame_MergeLeiaServer_Handler,
		},
		{
			MethodName: "AskForServers",
			Handler:    _StarwarsGame_AskForServers_Handler,
		},
		{
			MethodName: "AskedServer",
			Handler:    _StarwarsGame_AskedServer_Handler,
		},
		{
			MethodName: "GetCantSoldados",
			Handler:    _StarwarsGame_GetCantSoldados_Handler,
		},
		{
			MethodName: "MergeInformanteServer",
			Handler:    _StarwarsGame_MergeInformanteServer_Handler,
		},
		{
			MethodName: "GetLogs",
			Handler:    _StarwarsGame_GetLogs_Handler,
		},
		{
			MethodName: "PostMerge",
			Handler:    _StarwarsGame_PostMerge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/Starwars.proto",
}
