// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: proto/Calamardo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SavePlaysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ronda  int32  `protobuf:"varint,2,opt,name=ronda,proto3" json:"ronda,omitempty"`
	Jugada string `protobuf:"bytes,3,opt,name=jugada,proto3" json:"jugada,omitempty"`
}

func (x *SavePlaysRequest) Reset() {
	*x = SavePlaysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Calamardo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SavePlaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePlaysRequest) ProtoMessage() {}

func (x *SavePlaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Calamardo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePlaysRequest.ProtoReflect.Descriptor instead.
func (*SavePlaysRequest) Descriptor() ([]byte, []int) {
	return file_proto_Calamardo_proto_rawDescGZIP(), []int{0}
}

func (x *SavePlaysRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SavePlaysRequest) GetRonda() int32 {
	if x != nil {
		return x.Ronda
	}
	return 0
}

func (x *SavePlaysRequest) GetJugada() string {
	if x != nil {
		return x.Jugada
	}
	return ""
}

type SavePlaysReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exito bool `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
}

func (x *SavePlaysReply) Reset() {
	*x = SavePlaysReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Calamardo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SavePlaysReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavePlaysReply) ProtoMessage() {}

func (x *SavePlaysReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Calamardo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavePlaysReply.ProtoReflect.Descriptor instead.
func (*SavePlaysReply) Descriptor() ([]byte, []int) {
	return file_proto_Calamardo_proto_rawDescGZIP(), []int{1}
}

func (x *SavePlaysReply) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

type SendPlaysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ronda int32 `protobuf:"varint,2,opt,name=ronda,proto3" json:"ronda,omitempty"`
}

func (x *SendPlaysRequest) Reset() {
	*x = SendPlaysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Calamardo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPlaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlaysRequest) ProtoMessage() {}

func (x *SendPlaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Calamardo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlaysRequest.ProtoReflect.Descriptor instead.
func (*SendPlaysRequest) Descriptor() ([]byte, []int) {
	return file_proto_Calamardo_proto_rawDescGZIP(), []int{2}
}

func (x *SendPlaysRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SendPlaysRequest) GetRonda() int32 {
	if x != nil {
		return x.Ronda
	}
	return 0
}

type SendPlaysReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jugada string `protobuf:"bytes,1,opt,name=jugada,proto3" json:"jugada,omitempty"`
}

func (x *SendPlaysReply) Reset() {
	*x = SendPlaysReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Calamardo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPlaysReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlaysReply) ProtoMessage() {}

func (x *SendPlaysReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Calamardo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlaysReply.ProtoReflect.Descriptor instead.
func (*SendPlaysReply) Descriptor() ([]byte, []int) {
	return file_proto_Calamardo_proto_rawDescGZIP(), []int{3}
}

func (x *SendPlaysReply) GetJugada() string {
	if x != nil {
		return x.Jugada
	}
	return ""
}

type ReturnPlaysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReturnPlaysRequest) Reset() {
	*x = ReturnPlaysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Calamardo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnPlaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnPlaysRequest) ProtoMessage() {}

func (x *ReturnPlaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Calamardo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnPlaysRequest.ProtoReflect.Descriptor instead.
func (*ReturnPlaysRequest) Descriptor() ([]byte, []int) {
	return file_proto_Calamardo_proto_rawDescGZIP(), []int{4}
}

func (x *ReturnPlaysRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReturnPlaysReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jugada string `protobuf:"bytes,1,opt,name=jugada,proto3" json:"jugada,omitempty"`
}

func (x *ReturnPlaysReply) Reset() {
	*x = ReturnPlaysReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Calamardo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnPlaysReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnPlaysReply) ProtoMessage() {}

func (x *ReturnPlaysReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Calamardo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnPlaysReply.ProtoReflect.Descriptor instead.
func (*ReturnPlaysReply) Descriptor() ([]byte, []int) {
	return file_proto_Calamardo_proto_rawDescGZIP(), []int{5}
}

func (x *ReturnPlaysReply) GetJugada() string {
	if x != nil {
		return x.Jugada
	}
	return ""
}

type InsertPlaysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ronda  int32  `protobuf:"varint,2,opt,name=ronda,proto3" json:"ronda,omitempty"`
	Jugada string `protobuf:"bytes,3,opt,name=jugada,proto3" json:"jugada,omitempty"`
}

func (x *InsertPlaysRequest) Reset() {
	*x = InsertPlaysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Calamardo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertPlaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPlaysRequest) ProtoMessage() {}

func (x *InsertPlaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Calamardo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPlaysRequest.ProtoReflect.Descriptor instead.
func (*InsertPlaysRequest) Descriptor() ([]byte, []int) {
	return file_proto_Calamardo_proto_rawDescGZIP(), []int{6}
}

func (x *InsertPlaysRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InsertPlaysRequest) GetRonda() int32 {
	if x != nil {
		return x.Ronda
	}
	return 0
}

func (x *InsertPlaysRequest) GetJugada() string {
	if x != nil {
		return x.Jugada
	}
	return ""
}

type InsertPlaysReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exito bool `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
}

func (x *InsertPlaysReply) Reset() {
	*x = InsertPlaysReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Calamardo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertPlaysReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPlaysReply) ProtoMessage() {}

func (x *InsertPlaysReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Calamardo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPlaysReply.ProtoReflect.Descriptor instead.
func (*InsertPlaysReply) Descriptor() ([]byte, []int) {
	return file_proto_Calamardo_proto_rawDescGZIP(), []int{7}
}

func (x *InsertPlaysReply) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

type JoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Calamardo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Calamardo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_Calamardo_proto_rawDescGZIP(), []int{8}
}

func (x *JoinRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JoinReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdJugador int32 `protobuf:"varint,1,opt,name=id_jugador,json=idJugador,proto3" json:"id_jugador,omitempty"`
	Alive     bool  `protobuf:"varint,2,opt,name=alive,proto3" json:"alive,omitempty"`
	Round     int32 `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
}

func (x *JoinReply) Reset() {
	*x = JoinReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Calamardo_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinReply) ProtoMessage() {}

func (x *JoinReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Calamardo_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinReply.ProtoReflect.Descriptor instead.
func (*JoinReply) Descriptor() ([]byte, []int) {
	return file_proto_Calamardo_proto_rawDescGZIP(), []int{9}
}

func (x *JoinReply) GetIdJugador() int32 {
	if x != nil {
		return x.IdJugador
	}
	return 0
}

func (x *JoinReply) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *JoinReply) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

type StartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Etapa   int32  `protobuf:"varint,3,opt,name=etapa,proto3" json:"etapa,omitempty"`
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Calamardo_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Calamardo_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_proto_Calamardo_proto_rawDescGZIP(), []int{10}
}

func (x *StartRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StartRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartRequest) GetEtapa() int32 {
	if x != nil {
		return x.Etapa
	}
	return 0
}

type StartReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Started bool `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
}

func (x *StartReply) Reset() {
	*x = StartReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Calamardo_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReply) ProtoMessage() {}

func (x *StartReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Calamardo_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReply.ProtoReflect.Descriptor instead.
func (*StartReply) Descriptor() ([]byte, []int) {
	return file_proto_Calamardo_proto_rawDescGZIP(), []int{11}
}

func (x *StartReply) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

type JuegoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Jugada int32 `protobuf:"varint,2,opt,name=jugada,proto3" json:"jugada,omitempty"`
	Round  int32 `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Score  int32 `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	Etapa  int32 `protobuf:"varint,5,opt,name=etapa,proto3" json:"etapa,omitempty"`
}

func (x *JuegoRequest) Reset() {
	*x = JuegoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Calamardo_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JuegoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JuegoRequest) ProtoMessage() {}

func (x *JuegoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Calamardo_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JuegoRequest.ProtoReflect.Descriptor instead.
func (*JuegoRequest) Descriptor() ([]byte, []int) {
	return file_proto_Calamardo_proto_rawDescGZIP(), []int{12}
}

func (x *JuegoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *JuegoRequest) GetJugada() int32 {
	if x != nil {
		return x.Jugada
	}
	return 0
}

func (x *JuegoRequest) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *JuegoRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *JuegoRequest) GetEtapa() int32 {
	if x != nil {
		return x.Etapa
	}
	return 0
}

type JuegoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alive bool  `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	Round int32 `protobuf:"varint,2,opt,name=round,proto3" json:"round,omitempty"`
	Score int32 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Etapa int32 `protobuf:"varint,4,opt,name=etapa,proto3" json:"etapa,omitempty"`
}

func (x *JuegoReply) Reset() {
	*x = JuegoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Calamardo_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JuegoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JuegoReply) ProtoMessage() {}

func (x *JuegoReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Calamardo_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JuegoReply.ProtoReflect.Descriptor instead.
func (*JuegoReply) Descriptor() ([]byte, []int) {
	return file_proto_Calamardo_proto_rawDescGZIP(), []int{13}
}

func (x *JuegoReply) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *JuegoReply) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *JuegoReply) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *JuegoReply) GetEtapa() int32 {
	if x != nil {
		return x.Etapa
	}
	return 0
}

type MuerteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Etapa int32 `protobuf:"varint,2,opt,name=etapa,proto3" json:"etapa,omitempty"`
}

func (x *MuerteRequest) Reset() {
	*x = MuerteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Calamardo_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MuerteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuerteRequest) ProtoMessage() {}

func (x *MuerteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Calamardo_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuerteRequest.ProtoReflect.Descriptor instead.
func (*MuerteRequest) Descriptor() ([]byte, []int) {
	return file_proto_Calamardo_proto_rawDescGZIP(), []int{14}
}

func (x *MuerteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MuerteRequest) GetEtapa() int32 {
	if x != nil {
		return x.Etapa
	}
	return 0
}

type MuerteReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Alive bool  `protobuf:"varint,2,opt,name=alive,proto3" json:"alive,omitempty"`
}

func (x *MuerteReply) Reset() {
	*x = MuerteReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_Calamardo_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MuerteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuerteReply) ProtoMessage() {}

func (x *MuerteReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Calamardo_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuerteReply.ProtoReflect.Descriptor instead.
func (*MuerteReply) Descriptor() ([]byte, []int) {
	return file_proto_Calamardo_proto_rawDescGZIP(), []int{15}
}

func (x *MuerteReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MuerteReply) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

var File_proto_Calamardo_proto protoreflect.FileDescriptor

var file_proto_Calamardo_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x43, 0x61, 0x6c, 0x61, 0x6d, 0x61, 0x72, 0x64,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50,
	0x0a, 0x10, 0x53, 0x61, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6a, 0x75, 0x67, 0x61,
	0x64, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61,
	0x22, 0x26, 0x0a, 0x0e, 0x53, 0x61, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x69, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x65, 0x78, 0x69, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64,
	0x50, 0x6c, 0x61, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x72, 0x6f, 0x6e, 0x64, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x6e,
	0x64, 0x61, 0x22, 0x28, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x22, 0x24, 0x0a, 0x12,
	0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x2a, 0x0a, 0x10, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x50, 0x6c, 0x61, 0x79,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x22, 0x52,
	0x0a, 0x12, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6a, 0x75,
	0x67, 0x61, 0x64, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6a, 0x75, 0x67, 0x61,
	0x64, 0x61, 0x22, 0x28, 0x0a, 0x10, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x50, 0x6c, 0x61, 0x79,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78, 0x69, 0x74, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x65, 0x78, 0x69, 0x74, 0x6f, 0x22, 0x27, 0x0a, 0x0b,
	0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x56, 0x0a, 0x09, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69, 0x64, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f,
	0x72, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x4e, 0x0a,
	0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x74, 0x61, 0x70, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x74, 0x61, 0x70, 0x61, 0x22, 0x26, 0x0a,
	0x0a, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x65, 0x64, 0x22, 0x78, 0x0a, 0x0c, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x14, 0x0a,
	0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x74, 0x61,
	0x70, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x74, 0x61, 0x70, 0x61, 0x22,
	0x64, 0x0a, 0x0a, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x6c,
	0x69, 0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x74, 0x61, 0x70, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x65, 0x74, 0x61, 0x70, 0x61, 0x22, 0x35, 0x0a, 0x0d, 0x4d, 0x75, 0x65, 0x72, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x74, 0x61, 0x70, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x65, 0x74, 0x61, 0x70, 0x61, 0x22, 0x33, 0x0a, 0x0b,
	0x4d, 0x75, 0x65, 0x72, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x6c, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x76,
	0x65, 0x32, 0xee, 0x03, 0x0a, 0x0d, 0x43, 0x61, 0x6c, 0x61, 0x6d, 0x61, 0x72, 0x64, 0x6f, 0x47,
	0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x6f, 0x69, 0x6e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x47, 0x61, 0x6d, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x34,
	0x0a, 0x08, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x4d, 0x73, 0x67, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x06, 0x4d, 0x75, 0x65, 0x72, 0x74, 0x65, 0x12, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x75, 0x65, 0x72, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x75, 0x65,
	0x72, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0b, 0x49, 0x6e,
	0x73, 0x65, 0x72, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73,
	0x65, 0x72, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x43, 0x0a, 0x0b, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x12, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x50, 0x6c, 0x61,
	0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x09, 0x53, 0x61, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79,
	0x73, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x50, 0x6c,
	0x61, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x73,
	0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x6c, 0x61,
	0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x6c, 0x61, 0x62, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_Calamardo_proto_rawDescOnce sync.Once
	file_proto_Calamardo_proto_rawDescData = file_proto_Calamardo_proto_rawDesc
)

func file_proto_Calamardo_proto_rawDescGZIP() []byte {
	file_proto_Calamardo_proto_rawDescOnce.Do(func() {
		file_proto_Calamardo_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_Calamardo_proto_rawDescData)
	})
	return file_proto_Calamardo_proto_rawDescData
}

var file_proto_Calamardo_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_Calamardo_proto_goTypes = []interface{}{
	(*SavePlaysRequest)(nil),   // 0: proto.SavePlaysRequest
	(*SavePlaysReply)(nil),     // 1: proto.SavePlaysReply
	(*SendPlaysRequest)(nil),   // 2: proto.SendPlaysRequest
	(*SendPlaysReply)(nil),     // 3: proto.SendPlaysReply
	(*ReturnPlaysRequest)(nil), // 4: proto.ReturnPlaysRequest
	(*ReturnPlaysReply)(nil),   // 5: proto.ReturnPlaysReply
	(*InsertPlaysRequest)(nil), // 6: proto.InsertPlaysRequest
	(*InsertPlaysReply)(nil),   // 7: proto.InsertPlaysReply
	(*JoinRequest)(nil),        // 8: proto.JoinRequest
	(*JoinReply)(nil),          // 9: proto.JoinReply
	(*StartRequest)(nil),       // 10: proto.StartRequest
	(*StartReply)(nil),         // 11: proto.StartReply
	(*JuegoRequest)(nil),       // 12: proto.JuegoRequest
	(*JuegoReply)(nil),         // 13: proto.JuegoReply
	(*MuerteRequest)(nil),      // 14: proto.MuerteRequest
	(*MuerteReply)(nil),        // 15: proto.MuerteReply
}
var file_proto_Calamardo_proto_depIdxs = []int32{
	8,  // 0: proto.CalamardoGame.JoinGame:input_type -> proto.JoinRequest
	10, // 1: proto.CalamardoGame.StartGame:input_type -> proto.StartRequest
	12, // 2: proto.CalamardoGame.JuegoMsg:input_type -> proto.JuegoRequest
	14, // 3: proto.CalamardoGame.Muerte:input_type -> proto.MuerteRequest
	6,  // 4: proto.CalamardoGame.InsertPlays:input_type -> proto.InsertPlaysRequest
	4,  // 5: proto.CalamardoGame.ReturnPlays:input_type -> proto.ReturnPlaysRequest
	0,  // 6: proto.CalamardoGame.SavePlays:input_type -> proto.SavePlaysRequest
	2,  // 7: proto.CalamardoGame.SendPlays:input_type -> proto.SendPlaysRequest
	9,  // 8: proto.CalamardoGame.JoinGame:output_type -> proto.JoinReply
	11, // 9: proto.CalamardoGame.StartGame:output_type -> proto.StartReply
	13, // 10: proto.CalamardoGame.JuegoMsg:output_type -> proto.JuegoReply
	15, // 11: proto.CalamardoGame.Muerte:output_type -> proto.MuerteReply
	7,  // 12: proto.CalamardoGame.InsertPlays:output_type -> proto.InsertPlaysReply
	5,  // 13: proto.CalamardoGame.ReturnPlays:output_type -> proto.ReturnPlaysReply
	1,  // 14: proto.CalamardoGame.SavePlays:output_type -> proto.SavePlaysReply
	3,  // 15: proto.CalamardoGame.SendPlays:output_type -> proto.SendPlaysReply
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_Calamardo_proto_init() }
func file_proto_Calamardo_proto_init() {
	if File_proto_Calamardo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_Calamardo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SavePlaysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Calamardo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SavePlaysReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Calamardo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPlaysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Calamardo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPlaysReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Calamardo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnPlaysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Calamardo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnPlaysReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Calamardo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertPlaysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Calamardo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertPlaysReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Calamardo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Calamardo_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Calamardo_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Calamardo_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Calamardo_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JuegoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Calamardo_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JuegoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Calamardo_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MuerteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_Calamardo_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MuerteReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_Calamardo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_Calamardo_proto_goTypes,
		DependencyIndexes: file_proto_Calamardo_proto_depIdxs,
		MessageInfos:      file_proto_Calamardo_proto_msgTypes,
	}.Build()
	File_proto_Calamardo_proto = out.File
	file_proto_Calamardo_proto_rawDesc = nil
	file_proto_Calamardo_proto_goTypes = nil
	file_proto_Calamardo_proto_depIdxs = nil
}
